# Generated by Django 3.1.5 on 2021-01-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstats',
            name='type',
            field=models.CharField(choices=[('t', 'total'), ('h', 'home'), ('a', 'away')], default='t', max_length=10),
        ),
    ]
