# Generated by Django 3.2 on 2022-02-06 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='last_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
