# Generated by Django 3.2 on 2022-02-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_meta_last_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(choices=[('table', 'Tabelle'), ('points', 'Punkte'), ('highlights', 'Highlights')], max_length=16)),
                ('gd', models.IntegerField(default=0)),
                ('response', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'unique_together': {('request', 'user')},
            },
        ),
    ]
