# Generated by Django 3.1.5 on 2021-01-19 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210116_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
