# Generated by Django 3.1.5 on 2021-01-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_meta_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
