# Generated by Django 3.2 on 2022-02-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cache_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='curr_gd',
            field=models.IntegerField(default=0),
        ),
    ]
