# Generated by Django 3.1.5 on 2021-01-21 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_teamstats_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstats',
            name='four_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='three_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='two_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='zero_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meta',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 9, 26, 47, 244864, tzinfo=utc)),
        ),
    ]
