# Generated by Django 3.1.5 on 2021-01-21 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210121_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
