# Generated by Django 3.1.5 on 2021-01-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210121_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamStats',
            new_name='Stats',
        ),
    ]
