# Generated by Django 3.1.5 on 2021-01-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210121_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='preds',
            field=models.IntegerField(default=0),
        ),
    ]
